# # autoload -Uz is-at-least
# # is-at-least 5.0.6 && setopt NO_GLOBAL_RCS
# # if [ZSH_VERSION > ZSH 5.0.6 ]
# # http://www.thregr.org/~wavexx/rnd/20141010-zsh_show_ambiguity/
# zstyle ':completion:*' show-ambiguity true # TODO: add screenshot?

# cd ~user have never been useful to me, but named directories can be
# if expansion of the user home directory is really wanted, one can call
# _next_tags (^Xn)
#
# TODO:
# title expansion -tilde- completion context, should only complete named
# directories,
# use tag-order (zshcompsys) can bind _complete_help to see the tag order
# named directories should be verbose and print the full path on the right
zstyle ':completion:*:*:-tilde-:*' tag-order named-directories
# be careful to not add a '/' at the end of these directories, otherwise print
# -p '%~' does not work
hash -d ironysrc=~/projects/irony/irony-mode/server/src
hash -d irony=~/projects/irony/irony-mode
hash -d projects=~/projects

# TODO: check word-context and stuff section instead of this setting
WORDCHARS=''

# ignore some files during completion of most commands (fignore), except that
# these file we ignore will be the default candidates for rm
#
# for example, if we have: foo.c foo.o
# completion for cat will complete foo.c
# completion for rm will complete foo.o
fignore=(.o .pyc \~)            # see also ignored-patterns
zstyle ':completion:*:*:rm:*:*' file-patterns \
       "*(${(j:|:)fignore}):ignored-filed:ignored\ files" '%p:all-files'

# TODO: substring completion on C-<up>/C-<down>?
# for example for repo sync, just type:
# sync C-<up>
# repo sync RET

# TODO: add some colors
# http://linuxshellaccount.blogspot.fr/2008/12/color-completion-using-zsh-modules-on.html


# STOPPED AT
#
#            menu
#
#


# config initially generated by compinstall

# :completion:function:completer:command:argument:tag

# required before compinit to get menu-select
#
# > If you use the menu-select widget, which is part of the zsh/complist module,
# > you should make sure that that module is loaded before the call to compinit so
# > that that widget is also re-defined.
# -- man zshcompsys
zmodload zsh/complist

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' file-sort modification
zstyle ':completion:*' format '%B--- %d%b'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=**'
zstyle ':completion:*' max-errors 2 not-numeric
zstyle ':completion:*' menu select=1
zstyle ':completion:*' original false
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' prompt 'corrected (%e error(s))'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' verbose true
zstyle :compinstall filename "$ZUKODIR/completion.zsh"

autoload -Uz compinit
compinit
# End of lines added by compinstall
